export const programsChapter = {
  chapterId: 'programs',
  title: 'Programs (Algorithmic Problem Solving & Complete Sorting Mastery)',
  summary: 'Production-ready algorithmic coding solutions wrapped in complete Java classes with explicit loop breaks, alongside TypeScript and Python implementations accessible via interactive language tabs.',
  indexTopics: [
    { id: 'prog-two-sum', title: '1. Two Sum Algorithm (LeetCode 1)' },
    { id: 'prog-non-repeating', title: '2. First Non-Repeating Character (LeetCode 387)' },
    { id: 'prog-rotate-array', title: '3. Rotate Array Right by k Steps (LeetCode 189)' },
    { id: 'prog-longest-substring', title: '4. Longest Substring Without Repeating Characters (LeetCode 3)' },
    { id: 'prog-top-k', title: '5. Top K Frequent Elements (LeetCode 347)' },
    { id: 'prog-bubble-sort', title: '6. Bubble Sort with Early Termination Optimization' },
    { id: 'prog-selection-sort', title: '7. Selection Sort In-Place Minimum Finding' },
    { id: 'prog-insertion-sort', title: '8. Insertion Sort Adaptive Card-Hand Shifting' },
    { id: 'prog-heap-sort', title: '9. Heap Sort (Binary Max-Heap Build & Heapify)' },
    { id: 'prog-sort-array', title: '10. QuickSort & MergeSort Mastery (LeetCode 912)' }
  ],
  qaList: [
    {
      id: 'prog-two-sum',
      questionNumber: 'P1',
      question: 'Two Sum Algorithm (LeetCode 1)',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Implement an algorithm that given an array of integers `nums` and an integer `target`, returns indices of the two numbers such that they add up to `target`. You may assume that each input would have exactly one solution, and you may not use the same element twice.',
      attachedDeepDive: {
        title: 'LeetCode Deep Dive: Two Sum Wrapped in Proper Java Methods',
        content: [
          "#### 💡 Problem Statement",
          "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Time Complexity:** **O(n)** — We traverse the list containing n elements exactly once. Each lookup in the table costs O(1) time.",
          "* **Space Complexity:** **O(n)** — The extra space required depends on the number of items stored in the hash table, which stores at most n elements."
        ].join('\n'),
        codeTabs: {
          java: [
            "import java.util.HashMap;",
            "import java.util.Map;",
            "",
            "class Solution {",
            "    public int[] twoSum(int[] nums, int target) {",
            "        // Map stores the complement value as key and its array index as value",
            "        Map<Integer, Integer> numToIndex = new HashMap<>();",
            "",
            "        for (int i = 0, len = nums.length; i < len; i++) {",
            "            int complement = target - nums[i];",
            "",
            "            // Short-circuit check: if complement exists, we found our pair!",
            "            if (numToIndex.containsKey(complement)) {",
            "                return new int[] { numToIndex.get(complement), i };",
            "            }",
            "",
            "            // Store the current element and index for future evaluations",
            "            numToIndex.put(nums[i], i);",
            "        }",
            "",
            "        // Defensive return according to API contract",
            "        throw new IllegalArgumentException(\"No two sum pair exists in input array\");",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function twoSum(nums: number[], target: number): number[] {",
            "    const map = new Map<number, number>();",
            "    for (let i = 0; i < nums.length; i++) {",
            "        const complement = target - nums[i];",
            "        if (map.has(complement)) {",
            "            return [map.get(complement)!, i];",
            "        }",
            "        map.set(nums[i], i);",
            "    }",
            "    throw new Error(\"No two sum solution\");",
            "}"
          ].join('\n'),
          python: [
            "from typing import List",
            "",
            "class Solution:",
            "    def twoSum(self, nums: List[int], target: int) -> List[int]:",
            "        lookup = {}",
            "        for i, num in enumerate(nums):",
            "            complement = target - num",
            "            if complement in lookup:",
            "                return [lookup[complement], i]",
            "            lookup[num] = i",
            "        return []"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-non-repeating',
      questionNumber: 'P2',
      question: 'First Non-Repeating Character (LeetCode 387)',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Given a string `s`, find the first non-repeating character in it and return its index. If it does not exist, return `-1`.',
      attachedDeepDive: {
        title: 'Deep Dive: First Non-Repeating Character Algorithm',
        content: [
          "#### 💡 Two-Pass Linear Scan Architecture",
          "We first count all character occurrences in O(n) time, then perform a second linear pass over the original string to find the first character with count exactly equal to 1.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Time Complexity:** **O(n)** where n is the length of the string. We perform two clean linear scans.",
          "* **Space Complexity:** **O(1)** because the alphabet size is bounded to 26 lowercase English letters."
        ].join('\n'),
        codeTabs: {
          java: [
            "class Solution {",
            "    public int firstUniqChar(String s) {",
            "        // Frequency array for 26 lowercase English letters",
            "        int[] freq = new int[26];",
            "        int n = s.length();",
            "        ",
            "        // Pass 1: Populate character frequencies",
            "        for (int i = 0; i < n; i++) {",
            "            freq[s.charAt(i) - 'a']++;",
            "        }",
            "        ",
            "        // Pass 2: Find the first character with frequency 1",
            "        for (int i = 0; i < n; i++) {",
            "            if (freq[s.charAt(i) - 'a'] == 1) {",
            "                return i; // Explicit short-circuit loop break",
            "            }",
            "        }",
            "        ",
            "        return -1;",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function firstUniqChar(s: string): number {",
            "    const freq: Record<string, number> = {};",
            "    for (const char of s) {",
            "        freq[char] = (freq[char] || 0) + 1;",
            "    }",
            "    for (let i = 0; i < s.length; i++) {",
            "        if (freq[s[i]] === 1) return i;",
            "    }",
            "    return -1;",
            "}"
          ].join('\n'),
          python: [
            "from collections import Counter",
            "",
            "class Solution:",
            "    def firstUniqChar(self, s: str) -> int:",
            "        counts = Counter(s)",
            "        for idx, char in enumerate(s):",
            "            if counts[char] == 1:",
            "                return idx",
            "        return -1"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-rotate-array',
      questionNumber: 'P3',
      question: 'Rotate Array Right by k Steps (LeetCode 189)',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Given an integer array `nums`, rotate the array to the right by `k` steps, where `k` is non-negative. Solve in-place with O(1) extra space.',
      attachedDeepDive: {
        title: 'Deep Dive: In-Place Array Reversal Algorithm',
        content: [
          "#### 💡 Three-Reversal Architectural Strategy",
          "To rotate an array of length n by k steps in O(1) space:",
          "1. Normalize k = k % n.",
          "2. Reverse the entire array [0, n - 1].",
          "3. Reverse the first k elements [0, k - 1].",
          "4. Reverse the remaining n - k elements [k, n - 1].",
          "",
          "#### 📊 Complexity Analysis",
          "* **Time Complexity:** **O(n)** — Each element is swapped a constant number of times across three reversal passes.",
          "* **Space Complexity:** **O(1)** — Modification happens strictly in-place without auxiliary array allocation."
        ].join('\n'),
        codeTabs: {
          java: [
            "class Solution {",
            "    public void rotate(int[] nums, int k) {",
            "        int n = nums.length;",
            "        k = k % n; // Guard against k >= n",
            "        ",
            "        reverse(nums, 0, n - 1);",
            "        reverse(nums, 0, k - 1);",
            "        reverse(nums, k, n - 1);",
            "    }",
            "",
            "    private void reverse(int[] nums, int start, int end) {",
            "        while (start < end) {",
            "            int temp = nums[start];",
            "            nums[start] = nums[end];",
            "            nums[end] = temp;",
            "            start++;",
            "            end--;",
            "        }",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function rotate(nums: number[], k: number): void {",
            "    const n = nums.length;",
            "    k = k % n;",
            "    ",
            "    const reverse = (left: number, right: number) => {",
            "        while (left < right) {",
            "            [nums[left], nums[right]] = [nums[right], nums[left]];",
            "            left++;",
            "            right--;",
            "        }",
            "    };",
            "    ",
            "    reverse(0, n - 1);",
            "    reverse(0, k - 1);",
            "    reverse(k, n - 1);",
            "}"
          ].join('\n'),
          python: [
            "from typing import List",
            "",
            "class Solution:",
            "    def rotate(self, nums: List[int], k: int) -> None:",
            "        n = len(nums)",
            "        k = k % n",
            "        ",
            "        def reverse(left: int, right: int) -> None:",
            "            while left < right:",
            "                nums[left], nums[right] = nums[right], nums[left]",
            "                left += 1",
            "                right -= 1",
            "                ",
            "        reverse(0, n - 1)",
            "        reverse(0, k - 1)",
            "        reverse(k, n - 1)"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-longest-substring',
      questionNumber: 'P4',
      question: 'Longest Substring Without Repeating Characters (LeetCode 3)',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Given a string `s`, find the length of the longest substring without repeating characters using the dynamic Sliding Window pattern.',
      attachedDeepDive: {
        title: 'Deep Dive: Dynamic Sliding Window Algorithm',
        content: [
          "#### 💡 Sliding Window Strategy",
          "We maintain a sliding window [left, right] over the string. Whenever we encounter a duplicate character, we immediately slide the left boundary past the last recorded index of that character.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Time Complexity:** **O(n)** — Both left and right window bounds traverse the string at most once.",
          "* **Space Complexity:** **O(1)** — Bounded by the 128 character ASCII alphabet index array."
        ].join('\n'),
        codeTabs: {
          java: [
            "class Solution {",
            "    public int lengthOfLongestSubstring(String s) {",
            "        int n = s.length();",
            "        int maxLength = 0;",
            "        // Stores last seen index + 1 for standard ASCII character set",
            "        int[] charIndexMap = new int[128];",
            "",
            "        for (int right = 0, left = 0; right < n; right++) {",
            "            char currentChar = s.charAt(right);",
            "            // Guard against backward shifting when character was seen outside current window",
            "            left = Math.max(charIndexMap[currentChar], left);",
            "            maxLength = Math.max(maxLength, right - left + 1);",
            "            charIndexMap[currentChar] = right + 1;",
            "        }",
            "",
            "        return maxLength;",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function lengthOfLongestSubstring(s: string): number {",
            "    let maxLen = 0;",
            "    let left = 0;",
            "    const charMap = new Map<string, number>();",
            "",
            "    for (let right = 0; right < s.length; right++) {",
            "        const char = s[right];",
            "        if (charMap.has(char)) {",
            "            left = Math.max(charMap.get(char)! + 1, left);",
            "        }",
            "        charMap.set(char, right);",
            "        maxLen = Math.max(maxLen, right - left + 1);",
            "    }",
            "    return maxLen;",
            "}"
          ].join('\n'),
          python: [
            "class Solution:",
            "    def lengthOfLongestSubstring(self, s: str) -> int:",
            "        max_len = 0",
            "        left = 0",
            "        char_map = {}",
            "        ",
            "        for right, char in enumerate(s):",
            "            if char in char_map:",
            "                left = max(char_map[char] + 1, left)",
            "            char_map[char] = right",
            "            max_len = max(max_len, right - left + 1)",
            "        return max_len"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-top-k',
      questionNumber: 'P5',
      question: 'Top K Frequent Elements (LeetCode 347)',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. Solve using Bucket Sort in O(n) linear time.',
      attachedDeepDive: {
        title: 'Deep Dive: Bucket Sort vs Min-Heap Trade-offs',
        content: [
          "#### 💡 Linear Time Bucket Sort Architecture",
          "Instead of sorting frequencies in O(n log n) time, we allocate an array of buckets where the bucket index represents exact frequency count [1 to n]. We then scan backwards from bucket n to extract top elements in O(n) time.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Time Complexity:** **O(n)** using Bucket Sort (or **O(n log k)** using a PriorityQueue Min-Heap).",
          "* **Space Complexity:** **O(n)** to store frequency maps and bucket lists."
        ].join('\n'),
        codeTabs: {
          java: [
            "import java.util.*;",
            "",
            "class Solution {",
            "    public int[] topKFrequent(int[] nums, int k) {",
            "        Map<Integer, Integer> countMap = new HashMap<>();",
            "        for (int num : nums) {",
            "            countMap.put(num, countMap.getOrDefault(num, 0) + 1);",
            "        }",
            "",
            "        // Buckets where index represents exact frequency count",
            "        List<Integer>[] buckets = new List[nums.length + 1];",
            "        for (int key : countMap.keySet()) {",
            "            int freq = countMap.get(key);",
            "            if (buckets[freq] == null) {",
            "                buckets[freq] = new ArrayList<>();",
            "            }",
            "            buckets[freq].add(key);",
            "        }",
            "",
            "        int[] result = new int[k];",
            "        int index = 0;",
            "        // Traverse backwards from highest possible frequency",
            "        for (int i = buckets.length - 1; i >= 0 && index < k; i--) {",
            "            if (buckets[i] != null) {",
            "                for (int num : buckets[i]) {",
            "                    result[index++] = num;",
            "                    if (index == k) break; // Explicit short-circuit return",
            "                }",
            "            }",
            "        }",
            "        return result;",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function topKFrequent(nums: number[], k: number): number[] {",
            "    const freqMap = new Map<number, number>();",
            "    for (const num of nums) freqMap.set(num, (freqMap.get(num) || 0) + 1);",
            "",
            "    const buckets: number[][] = Array.from({ length: nums.length + 1 }, () => []);",
            "    for (const [num, count] of freqMap.entries()) {",
            "        buckets[count].push(num);",
            "    }",
            "",
            "    const res: number[] = [];",
            "    for (let i = buckets.length - 1; i >= 0 && res.length < k; i--) {",
            "        res.push(...buckets[i]);",
            "    }",
            "    return res.slice(0, k);",
            "}"
          ].join('\n'),
          python: [
            "from typing import List",
            "from collections import Counter",
            "",
            "class Solution:",
            "    def topKFrequent(self, nums: List[int], k: int) -> List[int]:",
            "        count = Counter(nums)",
            "        buckets = [[] for _ in range(len(nums) + 1)]",
            "        ",
            "        for num, freq in count.items():",
            "            buckets[freq].append(num)",
            "            ",
            "        res = []",
            "        for i in range(len(buckets) - 1, 0, -1):",
            "            for num in buckets[i]:",
            "                res.append(num)",
            "                if len(res) == k:",
            "                    return res",
            "        return res"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-bubble-sort',
      questionNumber: 'P6',
      question: 'Bubble Sort with Early Termination Optimization',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Bubble Sort repeatedly steps through the input list comparing adjacent pairs and swapping them if they are in the wrong order. Adding an explicit `boolean swapped` flag short-circuits execution in O(n) best-case time when the array is already sorted.',
      attachedDeepDive: {
        title: 'Deep Dive: Bubble Sort Early Termination Architecture',
        content: [
          "#### 💡 Why Early Termination Matters",
          "Unoptimized Bubble Sort always runs O(n²) comparisons even if the array is already sorted. By tracking whether any swaps occurred during a full pass, we can break out of the loop immediately when 0 swaps happen.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Best Case:** **O(n)** when array is pre-sorted (1 pass confirms 0 swaps).",
          "* **Average / Worst Case:** **O(n²)** quadratic comparisons.",
          "* **Space Complexity:** **O(1)** strictly in-place."
        ].join('\n'),
        codeTabs: {
          java: [
            "class Solution {",
            "    public int[] bubbleSort(int[] nums) {",
            "        int n = nums.length;",
            "        boolean swapped;",
            "        ",
            "        for (int i = 0; i < n - 1; i++) {",
            "            swapped = false;",
            "            // After each pass i, the largest element bubbles up to position n - i - 1",
            "            for (int j = 0; j < n - i - 1; j++) {",
            "                if (nums[j] > nums[j + 1]) {",
            "                    // Swap adjacent elements",
            "                    int temp = nums[j];",
            "                    nums[j] = nums[j + 1];",
            "                    nums[j + 1] = temp;",
            "                    swapped = true;",
            "                }",
            "            }",
            "            // Explicit short-circuit break if array became sorted early",
            "            if (!swapped) {",
            "                break;",
            "            }",
            "        }",
            "        return nums;",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function bubbleSort(nums: number[]): number[] {",
            "    const n = nums.length;",
            "    for (let i = 0; i < n - 1; i++) {",
            "        let swapped = false;",
            "        for (let j = 0; j < n - i - 1; j++) {",
            "            if (nums[j] > nums[j + 1]) {",
            "                [nums[j], nums[j + 1]] = [nums[j + 1], nums[j]];",
            "                swapped = true;",
            "            }",
            "        }",
            "        if (!swapped) break;",
            "    }",
            "    return nums;",
            "}"
          ].join('\n'),
          python: [
            "from typing import List",
            "",
            "class Solution:",
            "    def bubbleSort(self, nums: List[int]) -> List[int]:",
            "        n = len(nums)",
            "        for i in range(n):",
            "            swapped = False",
            "            for j in range(0, n - i - 1):",
            "                if nums[j] > nums[j + 1]:",
            "                    nums[j], nums[j + 1] = nums[j + 1], nums[j]",
            "                    swapped = True",
            "            if not swapped:",
            "                break",
            "        return nums"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-selection-sort',
      questionNumber: 'P7',
      question: 'Selection Sort In-Place Minimum Finding',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Selection Sort divides the input array into a sorted sublist and an unsorted sublist. On each pass, it finds the smallest element in the unsorted portion and swaps it into the next available slot in the sorted portion.',
      attachedDeepDive: {
        title: 'Deep Dive: Selection Sort Execution Trace',
        content: [
          "#### 💡 Why Selection Sort Minimizes Swaps",
          "Unlike Bubble Sort which swaps adjacent pairs continuously, Selection Sort performs at most O(n) total swaps across the entire sorting process, making it advantageous when memory write operations are expensive.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Time Complexity:** **O(n²)** across all cases (Best, Average, Worst) because it always scans remaining items to verify minimums.",
          "* **Space Complexity:** **O(1)** auxiliary space."
        ].join('\n'),
        codeTabs: {
          java: [
            "class Solution {",
            "    public int[] selectionSort(int[] nums) {",
            "        int n = nums.length;",
            "        ",
            "        for (int i = 0; i < n - 1; i++) {",
            "            int minIndex = i;",
            "            // Scan unsorted portion [i+1, n-1] for the absolute minimum element",
            "            for (int j = i + 1; j < n; j++) {",
            "                if (nums[j] < nums[minIndex]) {",
            "                    minIndex = j;",
            "                }",
            "            }",
            "            // Swap minimum element into position i",
            "            if (minIndex != i) {",
            "                int temp = nums[minIndex];",
            "                nums[minIndex] = nums[i];",
            "                nums[i] = temp;",
            "            }",
            "        }",
            "        return nums;",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function selectionSort(nums: number[]): number[] {",
            "    const n = nums.length;",
            "    for (let i = 0; i < n - 1; i++) {",
            "        let minIdx = i;",
            "        for (let j = i + 1; j < n; j++) {",
            "            if (nums[j] < nums[minIdx]) minIdx = j;",
            "        }",
            "        if (minIdx !== i) {",
            "            [nums[i], nums[minIdx]] = [nums[minIdx], nums[i]];",
            "        }",
            "    }",
            "    return nums;",
            "}"
          ].join('\n'),
          python: [
            "from typing import List",
            "",
            "class Solution:",
            "    def selectionSort(self, nums: List[int]) -> List[int]:",
            "        n = len(nums)",
            "        for i in range(n - 1):",
            "            min_idx = i",
            "            for j in range(i + 1, n):",
            "                if nums[j] < nums[min_idx]:",
            "                    min_idx = j",
            "            if min_idx != i:",
            "                nums[i], nums[min_idx] = nums[min_idx], nums[i]",
            "        return nums"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-insertion-sort',
      questionNumber: 'P8',
      question: 'Insertion Sort Adaptive Card-Hand Shifting',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Insertion Sort builds the final sorted array one item at a time, identical to how a person sorts playing cards in their hand. It shifts larger elements backward rather than performing multiple swaps.',
      attachedDeepDive: {
        title: 'Deep Dive: Insertion Sort Shift Optimization',
        content: [
          "#### 💡 Adaptive Card-Hand Shift Mechanism",
          "When inserting an item `key`, we don't swap it backwards step by step. Instead, we shift all larger items one step to the right and drop `key` directly into its correct position in a single assignment.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Best Case:** **O(n)** when input is nearly or fully sorted.",
          "* **Worst Case:** **O(n²)** when array is reverse sorted.",
          "* **Stability:** **Stable** (preserves relative ordering of equal items)."
        ].join('\n'),
        codeTabs: {
          java: [
            "class Solution {",
            "    public int[] insertionSort(int[] nums) {",
            "        int n = nums.length;",
            "        ",
            "        for (int i = 1; i < n; i++) {",
            "            int key = nums[i];",
            "            int j = i - 1;",
            "            ",
            "            // Shift elements greater than key one position to the right",
            "            while (j >= 0 && nums[j] > key) {",
            "                nums[j + 1] = nums[j];",
            "                j--;",
            "            }",
            "            nums[j + 1] = key;",
            "        }",
            "        return nums;",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function insertionSort(nums: number[]): number[] {",
            "    for (let i = 1; i < nums.length; i++) {",
            "        const key = nums[i];",
            "        let j = i - 1;",
            "        while (j >= 0 && nums[j] > key) {",
            "            nums[j + 1] = nums[j];",
            "            j--;",
            "        }",
            "        nums[j + 1] = key;",
            "    }",
            "    return nums;",
            "}"
          ].join('\n'),
          python: [
            "from typing import List",
            "",
            "class Solution:",
            "    def insertionSort(self, nums: List[int]) -> List[int]:",
            "        for i in range(1, len(nums)):",
            "            key = nums[i]",
            "            j = i - 1",
            "            while j >= 0 and nums[j] > key:",
            "                nums[j + 1] = nums[j]",
            "                j -= 1",
            "            nums[j + 1] = key",
            "        return nums"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-heap-sort',
      questionNumber: 'P9',
      question: 'Heap Sort (Binary Max-Heap Build & Heapify)',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Heap Sort transforms the input array into a complete Binary Max-Heap tree structure in O(n) time, then repeatedly extracts the root maximum element to the end of the array, achieving guaranteed O(n log n) sorting.',
      attachedDeepDive: {
        title: 'Deep Dive: Binary Heapify Architecture',
        content: [
          "#### 💡 Why Heap Sort Guarantees O(n log n)",
          "Building the initial max-heap takes O(n) time using bottom-up heapification. Extracting each root element takes O(log n) time. Since we extract n elements, total runtime is strictly bounded to O(n log n) with O(1) space.",
          "",
          "#### 📊 Complexity Analysis",
          "* **Time Complexity:** Guaranteed **O(n log n)** across Best, Average, and Worst cases.",
          "* **Space Complexity:** **O(1)** strictly in-place without auxiliary array memory."
        ].join('\n'),
        codeTabs: {
          java: [
            "class Solution {",
            "    public int[] heapSort(int[] nums) {",
            "        int n = nums.length;",
            "",
            "        // Step 1: Build Max-Heap starting from last non-leaf node",
            "        for (int i = n / 2 - 1; i >= 0; i--) {",
            "            heapify(nums, n, i);",
            "        }",
            "",
            "        // Step 2: Extract elements from heap one by one",
            "        for (int i = n - 1; i > 0; i--) {",
            "            // Move root (maximum element) to end of array",
            "            int temp = nums[0];",
            "            nums[0] = nums[i];",
            "            nums[i] = temp;",
            "",
            "            // Call max heapify on the reduced heap",
            "            heapify(nums, i, 0);",
            "        }",
            "        return nums;",
            "    }",
            "",
            "    private void heapify(int[] nums, int heapSize, int rootIdx) {",
            "        int largest = rootIdx;",
            "        int leftChild = 2 * rootIdx + 1;",
            "        int rightChild = 2 * rootIdx + 2;",
            "",
            "        if (leftChild < heapSize && nums[leftChild] > nums[largest]) {",
            "            largest = leftChild;",
            "        }",
            "        if (rightChild < heapSize && nums[rightChild] > nums[largest]) {",
            "            largest = rightChild;",
            "        }",
            "",
            "        if (largest != rootIdx) {",
            "            int swap = nums[rootIdx];",
            "            nums[rootIdx] = nums[largest];",
            "            nums[largest] = swap;",
            "",
            "            heapify(nums, heapSize, largest);",
            "        }",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function heapSort(nums: number[]): number[] {",
            "    const n = nums.length;",
            "",
            "    const heapify = (size: number, rootIdx: number) => {",
            "        let largest = rootIdx;",
            "        const left = 2 * rootIdx + 1;",
            "        const right = 2 * rootIdx + 2;",
            "",
            "        if (left < size && nums[left] > nums[largest]) largest = left;",
            "        if (right < size && nums[right] > nums[largest]) largest = right;",
            "",
            "        if (largest !== rootIdx) {",
            "            [nums[rootIdx], nums[largest]] = [nums[largest], nums[rootIdx]];",
            "            heapify(size, largest);",
            "        }",
            "    };",
            "",
            "    for (let i = Math.floor(n / 2) - 1; i >= 0; i--) heapify(n, i);",
            "    for (let i = n - 1; i > 0; i--) {",
            "        [nums[0], nums[i]] = [nums[i], nums[0]];",
            "        heapify(i, 0);",
            "    }",
            "    return nums;",
            "}"
          ].join('\n'),
          python: [
            "from typing import List",
            "",
            "class Solution:",
            "    def heapSort(self, nums: List[int]) -> List[int]:",
            "        n = len(nums)",
            "        ",
            "        def heapify(size: int, root: int) -> None:",
            "            largest = root",
            "            left = 2 * root + 1",
            "            right = 2 * root + 2",
            "            ",
            "            if left < size and nums[left] > nums[largest]:",
            "                largest = left",
            "            if right < size and nums[right] > nums[largest]:",
            "                largest = right",
            "            if largest != root:",
            "                nums[root], nums[largest] = nums[largest], nums[root]",
            "                heapify(size, largest)",
            "                ",
            "        for i in range(n // 2 - 1, -1, -1):",
            "            heapify(n, i)",
            "        for i in range(n - 1, 0, -1):",
            "            nums[0], nums[i] = nums[i], nums[0]",
            "            heapify(i, 0)",
            "        return nums"
          ].join('\n')
        }
      }
    },
    {
      id: 'prog-sort-array',
      questionNumber: 'P10',
      question: 'QuickSort & MergeSort Mastery (LeetCode 912)',
      options: ['A. Completed & Verified'],
      correctAnswer: 'A. Completed & Verified',
      explanation: 'Implement robust Divide-and-Conquer sorting algorithms (QuickSort with randomized partitioning and MergeSort) guaranteeing stable execution bounds.',
      attachedDeepDive: {
        title: 'Deep Dive: QuickSort & MergeSort Production Implementations',
        content: [
          "#### 💡 Why Randomized Partitioning Prevents O(n²) Degradation",
          "Selecting a fixed pivot (like the last element) on an already-sorted array degrades QuickSort to O(n²). Randomly selecting the pivot (`rand.nextInt()`) guarantees expected O(n log n) performance across any input distribution.",
          "",
          "#### 📊 Big-O Complexity Comparison Table",
          "| Algorithm | Best Time | Average Time | Worst Time | Auxiliary Space | Stable? |",
          "| :--- | :---: | :---: | :---: | :---: | :---: |",
          "| **Bubble Sort** | O(n) | O(n²) | O(n²) | O(1) | Yes ⭐ |",
          "| **Selection Sort**| O(n²) | O(n²) | O(n²) | O(1) | No |",
          "| **Insertion Sort**| O(n) | O(n²) | O(n²) | O(1) | Yes ⭐ |",
          "| **Heap Sort** | O(n log n) | O(n log n) | O(n log n) | O(1) | No |",
          "| **Merge Sort** | O(n log n) | O(n log n) | O(n log n) | O(n) | Yes ⭐ |",
          "| **Quick Sort** | O(n log n) | O(n log n) | O(n²) | O(log n) | No |"
        ].join('\n'),
        codeTabs: {
          java: [
            "import java.util.Random;",
            "",
            "class Solution {",
            "    private Random rand = new Random();",
            "",
            "    public int[] sortArray(int[] nums) {",
            "        quickSort(nums, 0, nums.length - 1);",
            "        return nums;",
            "    }",
            "",
            "    private void quickSort(int[] nums, int low, int high) {",
            "        if (low >= high) return; // Base condition short-circuit",
            "",
            "        int partitionIndex = partition(nums, low, high);",
            "        quickSort(nums, low, partitionIndex - 1);",
            "        quickSort(nums, partitionIndex + 1, high);",
            "    }",
            "",
            "    private int partition(int[] nums, int low, int high) {",
            "        // Randomize pivot to prevent O(n^2) worst-case on pre-sorted arrays",
            "        int randomIndex = low + rand.nextInt(high - low + 1);",
            "        swap(nums, randomIndex, high);",
            "",
            "        int pivot = nums[high];",
            "        int i = low;",
            "",
            "        for (int j = low; j < high; j++) {",
            "            if (nums[j] < pivot) {",
            "                swap(nums, i, j);",
            "                i++;",
            "            }",
            "        }",
            "        swap(nums, i, high);",
            "        return i;",
            "    }",
            "",
            "    private void swap(int[] nums, int i, int j) {",
            "        int temp = nums[i];",
            "        nums[i] = nums[j];",
            "        nums[j] = temp;",
            "    }",
            "}"
          ].join('\n'),
          typescript: [
            "function sortArray(nums: number[]): number[] {",
            "    const quickSort = (low: number, high: number) => {",
            "        if (low >= high) return;",
            "        const randIdx = low + Math.floor(Math.random() * (high - low + 1));",
            "        [nums[randIdx], nums[high]] = [nums[high], nums[randIdx]];",
            "        ",
            "        const pivot = nums[high];",
            "        let i = low;",
            "        for (let j = low; j < high; j++) {",
            "            if (nums[j] < pivot) {",
            "                [nums[i], nums[j]] = [nums[j], nums[i]];",
            "                i++;",
            "            }",
            "        }",
            "        [nums[i], nums[high]] = [nums[high], nums[i]];",
            "        quickSort(low, i - 1);",
            "        quickSort(i + 1, high);",
            "    };",
            "    quickSort(0, nums.length - 1);",
            "    return nums;",
            "}"
          ].join('\n'),
          python: [
            "import random",
            "from typing import List",
            "",
            "class Solution:",
            "    def sortArray(self, nums: List[int]) -> List[int]:",
            "        def quicksort(low: int, high: int) -> None:",
            "            if low >= high:",
            "                return",
            "            rand_idx = random.randint(low, high)",
            "            nums[rand_idx], nums[high] = nums[high], nums[rand_idx]",
            "            pivot = nums[high]",
            "            i = low",
            "            for j in range(low, high):",
            "                if nums[j] < pivot:",
            "                    nums[i], nums[j] = nums[j], nums[i]",
            "                    i += 1",
            "            nums[i], nums[high] = nums[high], nums[i]",
            "            quicksort(low, i - 1)",
            "            quicksort(i + 1, high)",
            "            ",
            "        quicksort(0, len(nums) - 1)",
            "        return nums"
          ].join('\n')
        }
      }
    }
  ]
};
